import re
import os

files = [
    r'd:\coding\order\codap_mobile\src\components\VLabs\AirQualityMeasurementLab.tsx',
    r'd:\coding\order\codap_mobile\src\components\VLabs\AirExperimentLab.tsx'
]

color_map = {
    'text-sky-800': 'text-[#528C46]',
    'bg-[#E0F6FF]': 'bg-[#FDFCF8]',
    'bg-slate-50': 'bg-[#FDFCF8]',
    'bg-slate-100': 'bg-[#C6E67D]/20',
    'bg-blue-50': 'bg-[#C6E67D]/10',
    'border-slate-300': 'border-[#C6E67D]/30',
    'border-slate-200': 'border-[#C6E67D]/30',
    'border-slate-100': 'border-[#C6E67D]/30',
    'border-blue-100': 'border-[#C6E67D]/30',
    'text-slate-800': 'text-[#0A110B]',
    'text-slate-700': 'text-[#0A110B]',
    'text-slate-600': 'text-[#6B7280]',
    'text-slate-500': 'text-[#6B7280]',
    'text-slate-400': 'text-[#6B7280]',
    'text-primary': 'text-[#528C46]',
    'bg-primary': 'bg-[#528C46]',
    'border-primary': 'border-[#528C46]',
    'bg-background': 'bg-[#FDFCF8]',
    'text-foreground': 'text-[#0A110B]',
    'text-muted-foreground': 'text-[#6B7280]',
    'border-border': 'border-[#C6E67D]',
    'border-blue-200': 'border-[#C6E67D]/30',
    'bg-blue-600': 'bg-[#528C46]',
    'border-blue-400': 'border-[#C6E67D]',
    'text-blue-600': 'text-[#528C46]',
    'bg-blue-100': 'bg-[#C6E67D]/20',
    'border-blue-500': 'border-[#528C46]'
}

for file_path in files:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Replace colors
    for old_color, new_color in color_map.items():
        content = content.replace(old_color, new_color)

    # Remove responsive prefixes
    content = re.sub(r'\b(sm|md|lg|xl):([a-zA-Z0-9_/-]+)\b', '', content)
    
    # Fix double spaces generated by prefix removal
    content = re.sub(r' +', ' ', content)
    
    # Replace layout logic that hides panels
    content = content.replace('${screen === "measuring" ? "hidden" : "flex"}', 'flex')
    content = content.replace('${screen === "measuring" ? "h-full flex-1" : ""}', 'flex-1')
    content = content.replace('${screen === "result" ? "hidden" : ""}', '')
    
    # AirQualityMeasurementLab specific layout adjustments
    content = content.replace('flex flex-col flex-row w-full h-screen', 'flex flex-row w-[100vw] h-[100vh] overflow-hidden')
    content = content.replace('flex flex-col flex-row', 'flex flex-row')
    
    # Enforce landscape proportions
    content = content.replace('h-[45vh] min-h-[350px] flex-1', 'flex-1')
    content = content.replace('h-0 flex-1', 'flex-1')
    content = content.replace('order-1', '')
    content = content.replace('order-2', '')
    
    # Replace some flex-cols to flex-rows where it's the main layout
    content = content.replace('flex-col flex-row w-full', 'flex-row w-[100vw]')
    content = content.replace('flex-col flex-row h-full w-full', 'flex-row h-full w-full')
    content = content.replace('flex-1 w-100 lg:w-112.5 shrink-0 bg-[#FDFCF8] border-t border-t-0 border-r', 'w-[40vw] shrink-0 bg-[#FDFCF8] border-r')
    
    # AirExperimentLab specific adjustments
    content = content.replace('className="relative flex flex-col flex-row w-full h-screen', 'className="relative flex flex-row w-[100vw] h-[100vh]')
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

print('Done')
